pip install GitPython
pip install guess_language
pip install guess-language
pip install ipaddresses
pip install jinja2
pip install lxml
pip install lz4
pip install markdown
pip install mitmproxy
pip install msgpack
pip install ndg-httpsclient
pip install ntlm
pip install pdfminer
pip install pebble
pip install phply
pip install psutil
pip install pyasn1
pip install pybloomfilter
pip install pyclamd
pip install PyGithub
pip install pyOpenSSL
pip install python-ntlm
pip install scapy
pip install subprocess32
pip install tblib
pip install termcolor
pip install tldextract
pip install vulndb
pip install vulners

