pip2 install Flask
pip2 install git.util
pip2 install github
pip2 install GitPython
pip2 install guess_language
pip2 install guess-language
pip2 install Halberd
pip2 install ipaddresses
pip2 install jinja2
pip2 install lxml
pip2 install lz4
pip2 install markdown
pip2 install mitmproxy
pip2 install msgpack
pip2 install ndg-httpsclient
pip2 install nltk
pip2 install ntlm
pip2 install pdfminer
pip2 install pebble
pip2 install phply
pip2 install psutil
pip2 install pyasn1
pip2 install pybloomfilter
pip2 install pyclamd
pip2 install PyGithub
pip2 install pyOpenSSL
pip2 install python-ntlm
pip2 install scapy
pip2 install scapy.config
pip2 install subprocess32
pip2 install tldextract
pip2 install vulners
pip2 install darts.util.lru
pip2 install future
pip2 install futures
pip2 install gitpython
pip2 install ndg-httpsclient
pip2 install ruamel_yaml
pip2 install tblib
pip2 install termcolor
pip2 install vulndb
pip2 install pebble
pip2 install lxml

