#!/usr/bin/python

'''
base64encode.py

Copyright 2006 Andres Riancho

This file is part of w3af, w3af.sourceforge.net .

w3af is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation version 2 of the License.

w3af is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with w3af; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

'''
from __future__ import print_function

import base64
import sys
import getopt

def usage():
    print('w3af - base64 encoder')
    print('')
    print('Options:')
    print('    -h  Print this help message.')
    print('    -e  String to be encoded.')
    print('')
    print('Example: base64encode -e encodeMeNow')
    
def main():
    
    try:
        opts, args = getopt.getopt(sys.argv[1:], "he:", ["help", "encode"])
    except getopt.GetoptError:
        # print help information and exit:
        usage()
        sys.exit(2)
    encode = None
    for o, a in opts:
        if o in ("-e", "--encode"):
            encode = a
        if o in ("-h", "--help"):
            usage()
            sys.exit()

    if encode is None:
            usage()
            sys.exit()
    print( base64.b64encode( encode) )
        
if __name__ == "__main__":
    main()
  
