<?xml version="1.0"?>
<definitions name="TemperatureService" targetNamespace="http://www.xmethods.net/sd/TemperatureService.wsdl"  xmlns:tns="http://www.xmethods.net/sd/TemperatureService.wsdl"   xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns="http://schemas.xmlsoap.org/wsdl/">
	<message name="getTempRequest">
		<part name="zipcode" type="xsd:string"/>
	</message>
	<message name="getTempResponse">
		<part name="return" type="xsd:float"/>
	</message>
	<portType name="TemperaturePortType">
		<operation name="getTemp">
			<input message="tns:getTempRequest"/>
			<output message="tns:getTempResponse"/>
		</operation>
	</portType>
	<binding name="TemperatureBinding" type="tns:TemperaturePortType">
		<soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
		<operation name="getTemp">
			<soap:operation soapAction=""/>
			<input>
				<soap:body use="encoded" namespace="urn:xmethods-Temperature" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
			</input>
			<output>
				<soap:body use="encoded" namespace="urn:xmethods-Temperature" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
			</output>
		</operation>
	</binding>
	<service name="TemperatureService">
		<documentation>Returns current temperature in a given U.S. zipcode  </documentation>
		<port name="TemperaturePort" binding="tns:TemperatureBinding">
			<soap:address location="http://services.xmethods.net:80/soap/servlet/rpcrouter"/>
		</port>
	</service>
</definitions>
